name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: true # Might fail if missing References

    - name: Build
      run: dotnet build --no-restore -c Debug
      continue-on-error: true # Might fail without game references in cloud

    - name: Get DLL
      id: find_dll
      run: |
        echo "path=$(find . -name 'Quantum Menu.dll' | head -n 1)" >> $GITHUB_OUTPUT

    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.18.${{ github.run_number }}
        name: Build 118.${{ github.run_number }}
        body: "Automated unique build #${{ github.run_number }} from the latest commit."
        files: ${{ steps.find_dll.outputs.path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
